-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 11:08:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mst_keu_akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mst_keu_akun` (
  `id_mst_akun` INT NOT NULL,
  PRIMARY KEY (`id_mst_akun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mst_keu_anggaran_versi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mst_keu_anggaran_versi` (
  `id_mst_anggaran_versi` VARCHAR(13) NOT NULL,
  `nama` VARCHAR(255) NULL,
  `deskripsi` TEXT NULL,
  `tanggal_dibuat` DATETIME NULL,
  PRIMARY KEY (`id_mst_anggaran_versi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mst_keu_anggaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mst_keu_anggaran` (
  `id_mst_anggaran` VARCHAR(16) NOT NULL,
  `id_mst_anggaran_parent` VARCHAR(16) NULL,
  `id_mst_akun` INT NULL,
  `kode_anggaran` VARCHAR(45) NULL,
  `uraian` VARCHAR(45) NULL,
  `tarif` VARCHAR(45) NULL,
  `id_mst_anggaran_versi` VARCHAR(13) NOT NULL,
  INDEX `fk_mst_keu_anggaran_mst_keu_anggaran_idx` (`id_mst_anggaran_parent` ASC),
  INDEX `fk_mst_keu_anggaran_mst_keu_akun1_idx` (`id_mst_akun` ASC),
  PRIMARY KEY (`id_mst_anggaran`),
  INDEX `fk_mst_keu_anggaran_mst_keu_anggaran_versi1_idx` (`id_mst_anggaran_versi` ASC),
  CONSTRAINT `fk_mst_keu_anggaran_mst_keu_anggaran`
    FOREIGN KEY (`id_mst_anggaran_parent`)
    REFERENCES `mydb`.`mst_keu_anggaran` (`id_mst_anggaran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mst_keu_anggaran_mst_keu_akun1`
    FOREIGN KEY (`id_mst_akun`)
    REFERENCES `mydb`.`mst_keu_akun` (`id_mst_akun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mst_keu_anggaran_mst_keu_anggaran_versi1`
    FOREIGN KEY (`id_mst_anggaran_versi`)
    REFERENCES `mydb`.`mst_keu_anggaran_versi` (`id_mst_anggaran_versi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cl_phc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cl_phc` (
  `code` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keu_transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keu_transaksi` (
  `id_transaksi` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_transaksi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keu_sts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keu_sts` (
  `id_sts` VARCHAR(16) NOT NULL,
  `tgl` DATE NULL,
  `code_pl_phc` INT NOT NULL,
  `nomor` VARCHAR(45) NULL,
  `total` INT NULL,
  `status` ENUM('disetor', 'draft') NULL,
  `ttd_pimpinan_nip` VARCHAR(45) NULL,
  `ttd_pimpinan_nama` VARCHAR(55) NULL,
  `ttd_penerima_nip` VARCHAR(45) NULL,
  `ttd_penerima_nama` VARCHAR(55) NULL,
  `ttd_penyetor_nip` VARCHAR(45) NULL,
  `ttd_penyetor_nama` VARCHAR(55) NULL,
  `catatan` TEXT NULL,
  `id_transaksi_pendapatan` VARCHAR(16) NULL,
  `id_transaksi_setor` VARCHAR(16) NULL,
  PRIMARY KEY (`id_sts`),
  INDEX `fk_keu_sts_cl_phc1_idx` (`code_pl_phc` ASC),
  INDEX `fk_keu_sts_keu_transaksi1_idx` (`id_transaksi_pendapatan` ASC),
  INDEX `fk_keu_sts_keu_transaksi2_idx` (`id_transaksi_setor` ASC),
  CONSTRAINT `fk_keu_sts_cl_phc1`
    FOREIGN KEY (`code_pl_phc`)
    REFERENCES `mydb`.`cl_phc` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keu_sts_keu_transaksi1`
    FOREIGN KEY (`id_transaksi_pendapatan`)
    REFERENCES `mydb`.`keu_transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keu_sts_keu_transaksi2`
    FOREIGN KEY (`id_transaksi_setor`)
    REFERENCES `mydb`.`keu_transaksi` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keu_sts_hasil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keu_sts_hasil` (
  `id_sts_hasil` INT NOT NULL,
  `id_mst_anggaran` VARCHAR(16) NOT NULL,
  `id_sts` VARCHAR(16) NOT NULL,
  `tarif` INT NULL,
  `vol` INT NULL,
  `jumlah` INT NULL,
  PRIMARY KEY (`id_sts_hasil`),
  INDEX `fk_keu_sts_hasil_mst_keu_anggaran1_idx` (`id_mst_anggaran` ASC),
  INDEX `fk_keu_sts_hasil_keu_sts1_idx` (`id_sts` ASC),
  CONSTRAINT `fk_keu_sts_hasil_mst_keu_anggaran1`
    FOREIGN KEY (`id_mst_anggaran`)
    REFERENCES `mydb`.`mst_keu_anggaran` (`id_mst_anggaran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keu_sts_hasil_keu_sts1`
    FOREIGN KEY (`id_sts`)
    REFERENCES `mydb`.`keu_sts` (`id_sts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keu_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keu_setting` (
  `id_setting` VARCHAR(13) NOT NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id_setting`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mst_keu_versi_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mst_keu_versi_status` (
  `id_mst_versi_status` INT NOT NULL,
  `id_mst_anggaran_versi` VARCHAR(13) NOT NULL,
  `cl_phc_code` INT NOT NULL,
  PRIMARY KEY (`id_mst_versi_status`),
  INDEX `fk_mst_keu_versi_status_mst_keu_anggaran_versi1_idx` (`id_mst_anggaran_versi` ASC),
  INDEX `fk_mst_keu_versi_status_cl_phc1_idx` (`cl_phc_code` ASC),
  CONSTRAINT `fk_mst_keu_versi_status_mst_keu_anggaran_versi1`
    FOREIGN KEY (`id_mst_anggaran_versi`)
    REFERENCES `mydb`.`mst_keu_anggaran_versi` (`id_mst_anggaran_versi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mst_keu_versi_status_cl_phc1`
    FOREIGN KEY (`cl_phc_code`)
    REFERENCES `mydb`.`cl_phc` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
